# creating a PV is k8 admin job
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # retain means don't delete data, 
                                         # Recycle means delete data and don't delete disk
                                         # Delete means delete data and delete disk
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0d267af8f7bbba7aa

--- # Create a PVC to use the PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # this is important, if you don't specify storage class name, then it will bind to PV which has empty storage class name 
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

--- # Create a pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: ebs-static