--- #Create Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: headless-svc-demo
    project: roboshop
spec:
  replicas: 4
  selector:
    matchLabels:
      purpose: headless-svc-demo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: headless-svc-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx

--- # Create a service of the deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

--- # Create a headless service of the deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-svc-demo
spec:
  # If a service clusterIP is None it is called headless service.
  clusterIP: None       
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80