--- # user configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"


--- #user deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: backend
    spec:
      containers:
      - name: user
        image: joindevops/user:v1
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: user-config
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10

--- ## Servicce
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  selector:
    project: roboshop
    component: user
    tier: backend
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Container port